/**
 * This file was automatically generated by @cosmwasm/ts-codegen@0.35.3.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run the @cosmwasm/ts-codegen generate command to regenerate this file.
 */

export type Uint128 = string;
export interface InstantiateMsg {
  admin?: string | null;
  lp_share_denom: string;
  max_distributions: number;
  min_bond: Uint128;
  tokens_per_power: Uint128;
  unbonder?: string | null;
  unbonding_periods: number[];
}
export type ExecuteMsg =
  | {
      delegate: {
        unbonding_period: number;
      };
    }
  | {
      rebond: {
        bond_from: number;
        bond_to: number;
        tokens: Uint128;
      };
    }
  | {
      unbond: {
        tokens: Uint128;
        unbonding_period: number;
      };
    }
  | {
      quick_unbond: {
        stakers: string[];
      };
    }
  | {
      unbond_all: {};
    }
  | {
      stop_unbond_all: {};
    }
  | {
      claim: {};
    }
  | {
      update_admin: {
        admin?: string | null;
      };
    }
  | {
      create_distribution_flow: {
        asset: AssetInfo;
        manager: string;
        rewards: [number, Decimal][];
      };
    }
  | {
      receive: Cw20ReceiveMsg;
    }
  | {
      distribute_rewards: {
        sender?: string | null;
      };
    }
  | {
      withdraw_rewards: {
        owner?: string | null;
        receiver?: string | null;
      };
    }
  | {
      delegate_withdrawal: {
        delegated: string;
      };
    }
  | {
      fund_distribution: {
        funding_info: FundingInfo;
      };
    };
export type AssetInfo =
  | {
      cw20_token: string;
    }
  | {
      smart_token: string;
    };
export type Decimal = string;
export type Binary = string;
export interface Cw20ReceiveMsg {
  amount: Uint128;
  msg: Binary;
  sender: string;
}
export interface FundingInfo {
  amount: Uint128;
  distribution_duration: number;
  start_time: number;
}
export type QueryMsg =
  | {
      claims: {
        address: string;
      };
    }
  | {
      staked: {
        address: string;
        unbonding_period: number;
      };
    }
  | {
      all_staked: {
        address: string;
      };
    }
  | {
      total_staked: {};
    }
  | {
      total_unbonding: {};
    }
  | {
      total_rewards_power: {};
    }
  | {
      rewards_power: {
        address: string;
      };
    }
  | {
      admin: {};
    }
  | {
      bonding_info: {};
    }
  | {
      annualized_rewards: {};
    }
  | {
      withdrawable_rewards: {
        owner: string;
      };
    }
  | {
      distributed_rewards: {};
    }
  | {
      undistributed_rewards: {};
    }
  | {
      delegated: {
        owner: string;
      };
    }
  | {
      distribution_data: {};
    }
  | {
      withdraw_adjustment_data: {
        addr: string;
        asset: AssetInfo;
      };
    }
  | {
      unbond_all: {};
    };
export interface AdminResponse {
  admin?: string | null;
}
export interface AllStakedResponse {
  stakes: StakedResponse[];
}
export interface StakedResponse {
  lp_share_denom: string;
  stake: Uint128;
  total_locked: Uint128;
  unbonding_period: number;
}
export type AssetInfoValidated =
  | {
      cw20_token: Addr;
    }
  | {
      smart_token: string;
    };
export type Addr = string;
export interface AnnualizedRewardsResponse {
  rewards: [number, AnnualizedReward[]][];
}
export interface AnnualizedReward {
  amount?: Decimal | null;
  info: AssetInfoValidated;
}
export interface BondingInfoResponse {
  bonding: BondingPeriodInfo[];
}
export interface BondingPeriodInfo {
  total_staked: Uint128;
  unbonding_period: number;
}
export type Expiration =
  | {
      at_height: number;
    }
  | {
      at_time: Timestamp;
    }
  | {
      never: {};
    };
export type Timestamp = Uint64;
export type Uint64 = string;
export interface ClaimsResponse {
  claims: Claim[];
}
export interface Claim {
  amount: Uint128;
  release_at: Expiration;
}
export interface DelegatedResponse {
  delegated: Addr;
}
export interface DistributedRewardsResponse {
  distributed: AssetValidated[];
  withdrawable: AssetValidated[];
}
export interface AssetValidated {
  amount: Uint128;
  info: AssetInfoValidated;
}
export interface DistributionDataResponse {
  distributions: [AssetInfoValidated, Distribution][];
}
export interface Distribution {
  distributed_total: Uint128;
  manager: Addr;
  reward_multipliers: [number, Decimal][];
  shares_leftover: number;
  shares_per_point: Uint128;
  withdrawable_total: Uint128;
}
export interface RewardsPowerResponse {
  rewards: [AssetInfoValidated, Uint128][];
}
export interface TotalStakedResponse {
  total_staked: Uint128;
}
export interface TotalUnbondingResponse {
  total_unbonding: Uint128;
}
export interface UnbondAllResponse {
  unbond_all: boolean;
}
export interface WithdrawableRewardsResponse {
  rewards: AssetValidated[];
}
export interface WithdrawAdjustment {
  shares_correction: number;
  withdrawn_rewards: Uint128;
}
